services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: ["./wait-for-it.sh", "mysql_server:3306", "--", "node", "app.js"]
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql:latest
    environment: 
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password